### ISSUE TITLE
View or download a mission’s Notes file

### ISSUE THREAD

**Issue by MBARIMike** [mbari-org/SeafloorMappingDB#79]
From the Use Case document:

> View or download a mission’s Notes file. (Getting to the directory, above, may be enough.)

The Notes are already viewable in the Mission detail view – and searchable for displaying Missions on the home page.

**Comment by jbpaduan** [comment]
This issue is not showing a CLOSE ISSUE button.

**Comment by MBARIMike** [comment]
I can close an Issue once I see a comment indicating that it's been solved.
